import type { Metadata } from "next";
import { Fraunces, Source_Sans_3 } from "next/font/google";
import ThemeRegistry from "@/app/theme-registry";
import { getServerLanguage } from "@/i18n/server";
import { I18nProvider } from "@/i18n/provider";
import "./globals.css";

const fraunces = Fraunces({
  subsets: ["latin"],
  weight: ["600", "700"],
  variable: "--font-display",
});

const sourceSans = Source_Sans_3({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  variable: "--font-body",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialLanguage = await getServerLanguage();

  return (
    <html lang={initialLanguage}>
      <body className={`${sourceSans.variable} ${fraunces.variable}`}>
        <I18nProvider initialLanguage={initialLanguage}>
          <ThemeRegistry>{children}</ThemeRegistry>
        </I18nProvider>
      </body>
    </html>
  );
}
